<br />
<b>Deprecated</b>:  Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/Users/tania/Facultate/Proiect Individual/music_competition/phpmyadmin/vendor/twig/twig/src/Node/Node.php</b> on line <b>161</b><br />
<br />
<b>Deprecated</b>:  Return type of Twig\Node\Node::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/Users/tania/Facultate/Proiect Individual/music_competition/phpmyadmin/vendor/twig/twig/src/Node/Node.php</b> on line <b>166</b><br />
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.1 setup script
 * Date: Sat, 04 Dec 2021 12:32:36 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'tania';
$cfg['Servers'][$i]['password'] = 'parola123';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'oYTlb~)\\:`P;M*p^#qyKggzIdy|\\dPQ!';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>